<?php

if(!class_exists('Vidsoe_Loader')){
    class Vidsoe_Loader {

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        //
        // public static
        //
        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        public static function install(){
            $content = <<<EOF
<?php
/*
Author: Vidsoe
Author URI: https://github.com/vidsoe
Description: This is automatically generated by the Vidsoe plugin. It is automatically disabled when disabling the main plugin.
Domain Path:
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Network: true
Plugin Name: Vidsoe Loader
Plugin URI: https://github.com/vidsoe/vidsoe
Text Domain: vidsoe-loader
Version: 0.2.13
*/

if(defined('WP_PLUGIN_DIR') and function_exists('trailingslashit')){
    if(file_exists(trailingslashit(WP_PLUGIN_DIR) . 'vidsoe/vidsoe.php')){
        if(in_array('vidsoe/vidsoe.php', (array) get_option('active_plugins')) or (function_exists('get_site_option') and array_key_exists('vidsoe/vidsoe.php', (array) get_site_option('active_sitewide_plugins')))){
            require_once(trailingslashit(WP_PLUGIN_DIR) . 'vidsoe/methods/vidsoe/load.php');
        }
    }
}

EOF;
            $file = trailingslashit(WPMU_PLUGIN_DIR) . 'vidsoe.php';
            if(file_exists($file) and md5($content) === md5_file($file)){
                return;
            }
            if(!is_dir(untrailingslashit(WPMU_PLUGIN_DIR))){
                @mkdir(untrailingslashit(WPMU_PLUGIN_DIR));
            }
            if(is_writable()){
                @file_put_contents($file, $content);
            }
        }

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        public static function uninstall(){
            $file = trailingslashit(WPMU_PLUGIN_DIR) . 'vidsoe/vidsoe.php';
            if(!file_exists($file)){
                return;
            }
            @unlink($file);
        }

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    }
}
